name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd auth && docker build -t aramhovhannisyna/auth .
      - run: docker login -u $DOCKER_USERNAME -p DOCKER_POASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_POASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push aramhovhannisyna/auth
